# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f877a9502e495b86ef6d4d19bb7306ad8ea8fb8b2b59209b63219b6d4f2050620e8c5435fb77995cd3c8d9c4f61d5f172b7a86bb223eb07a8758763052bc4a02

test:
  secret_key_base: 8c6e36ce804557e8f0fac36038012e03151f73f26dfc7aeb269fee5abc9acb61748384cfe5fae401cc471a9838c0efb9c01af6bba9a8c8ff5f8f36afdb4839bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
